version: '3.8'
services:
  pgdb:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data

  django:
    container_name: django_tenant
    build:
      context: ./
    image: django_test
    depends_on:
      - pgdb
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USER: postgres1
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - pgdb

volumes:
  pgdb:
    driver: local









